name: traffic_tactician
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.14
  - aom=3.9.1
  - attr=2.5.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - cloudpickle=3.1.1
  - contourpy=1.3.3
  - cpython=3.12.11
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - double-conversion=3.3.1
  - farama-notifications=0.0.4
  - ffmpeg=7.1.1
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gymnasium=1.0.0
  - h2=4.2.0
  - harfbuzz=11.3.3
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - intel-openmp=2022.0.1
  - jax-jumpy=1.0.0
  - jinja2=3.1.6
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - level-zero=1.24.0
  - libabseil=20250512.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libclang13=20.1.8
  - libcups=2.3.3
  - libdeflate=1.24
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.12.1
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopengl=1.7.0
  - libopenvino=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-intel-cpu-plugin=2025.2.0
  - libopenvino-intel-gpu-plugin=2025.2.0
  - libopenvino-intel-npu-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.5
  - libprotobuf=6.31.1
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libtiff=4.7.0
  - libudev1=257.7
  - libunwind=1.8.2
  - liburing=2.11
  - libusb=1.0.29
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.5
  - numpy=2.3.2
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.5.1
  - packaging=25.0
  - pandas=2.3.1
  - pango=1.56.4
  - pcre2=10.45
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pycparser=2.22
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt6-main=6.9.1
  - readline=8.2
  - requests=2.32.4
  - scipy=1.16.0
  - sdl2=2.32.54
  - sdl3=3.2.18
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.2
  - svt-av1=3.0.2
  - sympy=1.14.0
  - tbb=2022.2.0
  - tk=8.6.13
  - torchvision=0.18.1
  - tornado=6.5.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - attrs==25.3.0
      - click==8.2.1
      - dm-tree==0.1.9
      - ezdxf==1.4.2
      - fastjsonschema==2.21.1
      - fmpy==0.3.25
      - fsspec==2025.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - highway-env==1.10.1
      - imageio==2.37.0
      - immutabledict==4.2.1
      - iniconfig==2.1.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - lark==1.2.2
      - lxml==6.0.0
      - lz4==4.4.4
      - markdown==3.8.2
      - mouseinfo==0.1.3
      - msgpack==1.1.1
      - nbformat==5.10.4
      - ormsgpack==1.7.0
      - ortools==9.14.6206
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - protobuf==6.31.1
      - psutil==7.0.0
      - pulp==3.2.2
      - pyarrow==21.0.0
      - pyautogui==0.9.54
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygame==2.6.1
      - pygetwindow==0.0.9
      - pygments==2.19.2
      - pymsgbox==1.0.9
      - pyperclip==1.9.0
      - pyproj==3.7.1
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - pytest==8.4.1
      - python3-xlib==0.15
      - pytweening==1.2.0
      - ray==2.48.0
      - referencing==0.36.2
      - rpds-py==0.26.0
      - rtree==1.4.0
      - sentry-sdk==2.34.1
      - smmap==5.0.2
      - stable-baselines3==2.7.0
      - sumolib==1.24.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - texttest==4.4.4
      - tqdm==4.67.1
      - traci==1.24.0
      - traitlets==5.14.3
      - typing-inspection==0.4.1
      - wandb==0.21.0
      - werkzeug==3.1.3
      - wrapt==1.17.2